name: Build and Publish

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - name: Publish
        if: false
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: browser           # After publish tag this channel as 'HTML5 / Playable in browser'
          ITCH_GAME: babylon-example # Use your project's name on itch.io
          ITCH_USER: oktinaut        # Replace with your itch.io username
          PACKAGE: dist/